# Generated by Django 5.0.4 on 2024-05-21 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phno',
            new_name='pno',
        ),
    ]
